name: Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        working-directory: ./typescript-version
      - run: yarn build --base=/materio-vuetify-vuejs-admin-template-free/demo/
        working-directory: ./typescript-version
      - name: Upload dist content via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: ./typescript-version/dist
          target: ${{ secrets.PROJECTDIR }}
#       - name: Replace old demo
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           USERNAME: ${{ secrets.USERNAME }}
#           PORT: ${{ secrets.PORT }}
#           KEY: ${{ secrets.SSHKEY }}
#           script: mkdir -p ${{ secrets.PROJECTDIR }} && if [ -d ${{ secrets.PROJECTDIR }}/demo ]; then mv ${{ secrets.PROJECTDIR }}/demo ${{ secrets.PROJECTDIR }}/demo-old; fi && mv ${{ secrets.PROJECTDIR }}/dist ${{ secrets.PROJECTDIR }}/demo && rm -rf ${{ secrets.PROJECTDIR }}/demo-old
